version: 2
jobs:
  "node-12":
    docker:
      - image: circleci/node:12
    working_directory: ~/launchpad
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - "node-12"
